# SPDX-FileCopyrightText: 2025 Lorenz Wildberg
# SPDX-License-Identifier: LGPL-2.1

[library]
description = "Vala GIR parser"
authors = "Jan-Willem Harmannij"
license = "LGPL-2.1"
browse_url = "https://gitlab.gnome.org/GNOME/gtk/"
repository_url = "https://gitlab.gnome.org/GNOME/gtk.git"
website_url = "https://www.gtk.org"

# List the dependencies using their GIR namespace
dependencies = [
  "GObject-2.0",
  "Gee-0.8",
]

[dependencies."GObject-2.0"]
name = "GObject"
description = "The base type system library"
docs_url = "https://developer.gnome.org/gobject/stable"

[dependencies."Gee-0.8"]
name = "Libgee"
description = "The base type system library"
docs_url = "https://developer.gnome.org/gobject/stable"

[source-location]
# The base URL for the web UI
base_url = "https://gitlab.gnome.org/GNOME/gtk/-/blob/master/"
# The format for links, using "filename" and "line" for the format
file_format = "{filename}#L{line}"
