name: Build project and publish docs

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Checkout vala-gir-parser repository
        uses: actions/checkout@v4
        with:
          repository: 'jwharm/vala-gir-parser'
          path: 'vala-gir-parser'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pip packages
        run: pip3 install meson ninja gi-docgen

      - name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: >
            valac
            valadoc
            pkg-config
            libgee-0.8-dev
            libvala-0.56-dev
            libgirepository1.0-dev
          version: 1.0

      - name: Run Meson build
        working-directory: vala-gir-parser/
        run: |
          meson setup builddir
          meson compile -C builddir

      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'vala-gir-parser/builddir/docs/valagir-1.0'

  pages:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

